#!/usr/bin/env python3
"""
Regenerate BEGIN/END PROVENANCE blocks in README.md and paper_*/README.md.
=============================================================================
Type:           AUDIT
Produces:       rewrites provenance blocks only
Reads:          scripts/claims_registry.json
Role:           PMAP
=============================================================================
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(line_buffering=True)

ROOT = Path(__file__).resolve().parents[1]
REG = Path(__file__).resolve().parent / "claims_registry.json"
BEGIN = "<!-- BEGIN PROVENANCE (generated by scripts/provenance_map.py) -->"
END = "<!-- END PROVENANCE -->"


def render_block(claims: list[dict], title: str) -> str:
    by_paper: dict[str, list] = {}
    for c in claims:
        by_paper.setdefault(c.get("paper", "?"), []).append(c)
    lines = [BEGIN, ""]
    lines.append(
        f"{title} Every registered headline quantity maps to a committed "
        "artefact expression. Generated by `scripts/provenance_map.py` from "
        "`scripts/claims_registry.json` — do not hand-edit it."
    )
    lines.append("")
    lines.append(f"- claim call sites: **{len(claims)}**")
    lines.append("")
    lines.append("| paper | section | manuscript quantity | where | produced by |")
    lines.append("|---|---|---|---|---|")
    for paper in sorted(by_paper.keys()):
        for c in by_paper[paper]:
            comp = c.get("computed")
            comp_s = f"{comp:.6g}" if isinstance(comp, float) else str(comp)[:80]
            lines.append(
                f"| {c.get('paper')} | {c.get('section')} | {c.get('quantity')} | "
                f"{c.get('where')} | `{comp_s}` |"
            )
    lines.append("")
    lines.append(
        "Register new numbers in `scripts/verify_claims.py`, re-run "
        "`run_all_audits.py`, then let this script rewrite the block."
    )
    lines.append(END)
    return "\n".join(lines) + "\n"


def replace_block(path: Path, block: str) -> bool:
    if not path.exists():
        return False
    text = path.read_text(encoding="utf-8")
    if BEGIN in text and END in text:
        i0 = text.index(BEGIN)
        i1 = text.index(END) + len(END)
        new = text[:i0] + block + text[i1:]
    else:
        if not text.endswith("\n"):
            text += "\n"
        new = text + "\n## Data provenance\n\n" + block
    if new != text:
        path.write_text(new, encoding="utf-8")
        return True
    return False


def main() -> int:
    if not REG.exists():
        print("provenance_map: missing claims_registry.json — run verify_claims.py first")
        return 1
    data = json.loads(REG.read_text(encoding="utf-8"))
    claims = data.get("claims") or []

    # root README: all claims
    root_block = render_block(
        claims,
        f"All papers (A–F). Failures in last run: **{data.get('n_fail', '?')}**.",
    )
    replace_block(ROOT / "README.md", root_block)

    # per-paper READMEs: only that paper + shared labels mapped loosely
    paper_map = {
        "A": ["A"],
        "B": ["B", "shared"],
        "C": ["C", "B", "shared"],
        "D": ["D"],
        "E": ["E"],
        "F": ["F"],
    }
    for letter, papers in paper_map.items():
        subset = [c for c in claims if c.get("paper") in papers]
        readme = ROOT / f"paper_{letter.lower()}" / "README.md"
        block = render_block(
            subset,
            f"Claims registered for Paper {letter} (includes shared anchors where relevant).",
        )
        if replace_block(readme, block):
            print(f"provenance_map: rewrote {readme.parent.name}/README.md ({len(subset)} claims)")
        else:
            print(f"provenance_map: skip {readme} (missing)")

    print(f"provenance_map: root README block ({len(claims)} claims)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
