#!/usr/bin/env python3
"""
S21: REDEM-SSM P3 - M4 gentle routing + M5 state-norm homeostat.
=============================================================================
Type:           ML (torch CPU; no @njit; Pool only around independent trials)
Experiment:     S21 (Paper D P3): two mechanism tests on the diagonal-SSM
                host, both within the RLS-only constraint (no gradient):

E1 (M4 "gentle wins"): P2 showed A3 routing (abrupt specialist switch)
improves forgetting but PAYS a stream cost (+0.38..+4.08 ppl - the
specialization-vs-lag tradeoff). E1 tests whether SOFT routing - a
continuous softmax weighting of the two specialists by their EMA
distances (no hysteresis flip) - smooths the transition and reduces the
stream penalty while keeping the forgetting gain:
  A1        : bare single RLS readout (replication baseline)
  A3-abrupt : P2's routing (hysteresis flip, P2 replication)
  A3-soft   : softmax-distance weighted routing (gentle)
tau_m = 500 (P2's sweet spot). Task/seed rules/metrics verbatim from s18.

E2 (M5 state-norm homeostat): P2 found the FULL whitened-state EMA is a
non-stationary domain statistic (slow channels, tau up to 3000, accumulate
over the stream; the detector never flips - fixed by masking to fast
channels). E2 tests the homeostat alternative: a closed-loop controller
monitors the whitened-state norm and adjusts the effective time step
(Delta_t) to hold the norm in a target band around sqrt(N) - the
whitening's unit-variance intent:
  h_t = A^{Delta_t} h_{t-1} + B e_{t-1}
  Delta_t = clip(Delta_{t-1} + eta (||h_w|| - U), 1, Delta_max)
Arms: BARE vs REG, clean vs disturbed (a state spike injected at the
first switch). Metrics (mechanism-level, honest scope): full-state-EMA
detector flips (5/5 known switches), norm mean/max/final, recovery tokens
to return to the band after the spike, Delta_t activity.

Predictions (Paper D, P3/P4):
  P3: gradual M4 beats abrupt on stream ppl (soft < abrupt, n>=6/10),
      forgetting not degraded.
  P4: M5 regulation keeps the state norm in band (and restores the
      full-state EMA detector to 5/5); bare drifts out of band and does
      not recover from the disturbance.
Falsified iff the predicted direction reverses (reported honestly).

Output files:
  data/s21_ssm_m4_m5_v1.csv
  data/s21_ssm_m4_m5_v1.json

Usage: python s21_ssm_m4_m5.py [--quick] [--sequential]
       python s21_ssm_m4_m5.py --frozen-p-probe
         runs only the A3-soft-frozenW isolation arm (weights frozen,
         inverse covariances refreshed) and writes
         data/s37_dormant_p_probe_v1.json; the E1/E2 artifacts are untouched
"""
import os
import sys
import time
import csv
import json

os.environ.setdefault('PYTHONUNBUFFERED', '1')
if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(line_buffering=True)
    sys.stderr.reconfigure(line_buffering=True)

import numpy as np
import torch
from multiprocessing import Pool, cpu_count

from s19_ssm_rls_readout import (gen_drift_stream, gen_stream,
                                 sample_substrate, whiten_scale,
                                 VOCAB, N_STATE, SEG_LEN, N_SEGMENTS,
                                 HOLDOUT_LEN, BIAS_A, BIAS_B,
                                 RLS_LAMBDA, RLS_DELTA, SEED_SCALE,
                                 SEED_OFF)
from s20_ssm_m3_routing import (fast_mask_of, gate_estimate,
                                GATE_MARGIN, T_ADAPT_WINDOW, STEADY_WINDOW,
                                T_ADAPT_RATIO)
from per_token_io import save_stream_and_holdout

torch.set_num_threads(1)   # per-worker; Pool gives process-level parallelism

# ========================== Fixed parameters ==========================
TAU_M = 500.0              # E1 metadata timescale (P2 sweet spot)
N_SEEDS = 10
REF_LEN = 1500

# E2 homeostat
E2_U = float(np.sqrt(N_STATE))     # target whitened-state norm (~sqrt(N))
E2_ETA = 0.05
E2_DT_MAX = 10.0
E2_BAND = 1.05             # recovery threshold: norm <= U*BAND after spike
E2_SPIKE = 10.0            # disturbance magnitude at the first switch

# Frozen-weight probe result quoted in Paper D Section 4.3 (regenerated by
# `--frozen-p-probe`, written to data/s37_dormant_p_probe_v1.json). The arm
# leaves W at its uniform prior, so its stream ppl is exactly V=32 -- chance
# for a 32-symbol vocabulary -- i.e. refreshing P alone learns nothing.
S37_CHANCE_PPL = 32.0            # 1/(1/VOCAB), the uniform-prior CE

# M3 detector tracking quoted in Paper D Section 4.2 (regenerated by
# `s20_ssm_m3_routing.py`, column `switches_detected` of
# data/s20_ssm_m3_routing_v1.csv). Mean detections of the 5 known switches
# over 10 seeds, A2 and A3 alike (the detector is shared).
S20_DETECTED = {200.0: 2.80, 500.0: 0.30, 1000.0: 0.00, 2000.0: 0.00}
S20_FORGET_GAIN_WHEN_DETECTED = 1.99   # |A3-A1| forgetting, seeds with >=1 det
S20_FORGET_GAIN_WHEN_NOT = 0.98        # |A3-A1| forgetting, seeds with 0 det

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = os.path.join(SCRIPT_DIR, '..', 'data')
CSV_PATH = os.path.join(DATA_DIR, 's21_ssm_m4_m5_v1.csv')
JSON_PATH = os.path.join(DATA_DIR, 's21_ssm_m4_m5_v1.json')


# ========================== E1: readout machinery (s20 reuse) ==========================

def make_readout(F):
    W = torch.zeros(VOCAB, F, dtype=torch.float64)
    W[:, -1] = 1.0 / VOCAB
    P = torch.eye(F, dtype=torch.float64) / RLS_DELTA
    return W, P


def rls_update(W, P, phi, target, err_scale):
    e = err_scale * (target - (W @ phi))
    g = P @ phi
    k = g / (RLS_LAMBDA + float(phi @ g))
    W = W + torch.outer(e, k)
    P = (P - torch.outer(k, phi) @ P) / RLS_LAMBDA
    return W, P


def rls_refresh_P(P, phi):
    """Dormant-covariance refresh: advance the inverse covariance on the
    current feature stream with the weights frozen (zero error). Returns P
    only; the caller leaves W untouched."""
    g = P @ phi
    k = g / (RLS_LAMBDA + float(phi @ g))
    return (P - torch.outer(k, phi) @ P) / RLS_LAMBDA


# Guard for the frozen-weight arm: W must equal its initial value exactly.
# make_readout initialises W to a uniform prior (all columns zero except the
# bias 1/VOCAB), so the invariant is a direct comparison against a freshly
# initialised readout -- a magnitude test cannot distinguish "untouched" from
# "trained", because both states span 0..1/VOCAB.
FROZEN_W_TOL = 1e-12


def assert_W_still_frozen(W, W_init, arm, seed):
    if arm != 'A3-soft-frozenW':
        return
    drift = float((W - W_init).abs().max())
    if drift > FROZEN_W_TOL:
        raise AssertionError(
            f"{arm} seed {seed}: readout weights are not frozen "
            f"(max|W - W_init| = {drift:.3e}) -- the arm would silently "
            "reproduce A3-soft instead of testing dormancy")


def refs_fast(seed, A, B, scale):
    """Fast-channel metadata references (P2 host)."""
    fm = fast_mask_of(A)
    refs = []
    for d in range(2):
        rs = gen_stream(seed * 31 + d * 131 + 7, 1 if d == 0 else 7,
                        REF_LEN, BIAS_A if d == 0 else BIAS_B)
        h = torch.zeros(N_STATE, dtype=torch.float64)
        acc = torch.zeros(N_STATE, dtype=torch.float64)
        for t in range(REF_LEN):
            h = A * h + B[:, rs[t]]
            acc = acc + h * scale
        refs.append((acc / REF_LEN)[fm])
    return refs


def run_e1(args):
    """(arm, tau_m, seed) -> E1 metrics. Top-level; unbuffered."""
    if hasattr(sys.stdout, 'reconfigure'):
        sys.stdout.reconfigure(line_buffering=True)
        sys.stderr.reconfigure(line_buffering=True)
    arm, tau_m, seed = args
    t0 = time.time()

    torch.manual_seed(seed * SEED_SCALE + SEED_OFF)
    A, B = sample_substrate(seed, 'CV')
    scale = whiten_scale(A)
    fm = fast_mask_of(A)
    stream, domains = gen_drift_stream(seed)
    T = stream.shape[0]
    F = N_STATE + 1

    refs = refs_fast(seed, A, B, scale)
    sep = float(torch.norm(refs[0] - refs[1]))
    kappa = 0.5 * max(sep, 1e-6)      # softmax temperature (gentle scale)

    if arm == 'A1':
        W, P = make_readout(F)
        W0 = W1 = P0 = P1 = None
        W0_init = W1_init = None
    else:
        W0, P0 = make_readout(F)
        W1, P1 = make_readout(F)
        W = P = None
        W0_init = W0.clone()
        W1_init = W1.clone()

    slow = refs[0].clone()
    prev_est = 0
    last_switch_t = -10 ** 9

    ce = np.empty(T, dtype=np.float64)
    ce[:] = np.nan
    ce_unc = np.empty(T, dtype=np.float64)
    ce_unc[:] = np.nan
    nneg = 0
    nclip = 0
    n_unc_undef = 0
    h = torch.zeros(N_STATE, dtype=torch.float64)

    for t in range(1, T):
        h = A * h + B[:, stream[t - 1]]
        hw = h * scale

        if arm == 'A1':
            y_hat = (W @ torch.cat([B[:, stream[t - 1]],
                                    torch.ones(1, dtype=torch.float64)]))
            y_tok = y_hat[stream[t]]
            p_t = float(y_tok.clamp(min=1e-12, max=1.0))
            yt = float(y_tok)
            if yt <= 0.0:
                nneg += 1
            if yt <= 1e-12:
                nclip += 1
            if yt > 0.0:
                ce_unc[t] = -np.log(yt)
            else:
                n_unc_undef += 1
            ce[t] = -np.log(p_t)
            target = torch.zeros(VOCAB, dtype=torch.float64)
            target[stream[t]] = 1.0
            W, P = rls_update(W, P,
                              torch.cat([B[:, stream[t - 1]],
                                         torch.ones(1,
                                                    dtype=torch.float64)]),
                              target, 1.0)
        else:
            lam = 1.0 / tau_m
            slow = (1.0 - lam) * slow + lam * hw[fm]
            if arm == 'A3-abrupt':
                est = gate_estimate(slow, refs, prev_est, GATE_MARGIN)
                if est != prev_est:
                    last_switch_t = t
                    prev_est = est
                w0 = 1.0 if est == 0 else 0.0
                w1 = 1.0 - w0
            else:  # A3-soft: continuous softmax weights (no flip)
                d0 = float(torch.norm(slow - refs[0]))
                d1 = float(torch.norm(slow - refs[1]))
                w1 = 1.0 / (1.0 + np.exp((d1 - d0) / kappa))
                w0 = 1.0 - w1

            phi = torch.cat([B[:, stream[t - 1]],
                             torch.ones(1, dtype=torch.float64)])
            y_hat = w0 * (W0 @ phi) + w1 * (W1 @ phi)
            y_tok = y_hat[stream[t]]
            p_t = float(y_tok.clamp(min=1e-12, max=1.0))
            yt = float(y_tok)
            if yt <= 0.0:
                nneg += 1
            if yt <= 1e-12:
                nclip += 1
            if yt > 0.0:
                ce_unc[t] = -np.log(yt)
            else:
                n_unc_undef += 1
            ce[t] = -np.log(p_t)
            target = torch.zeros(VOCAB, dtype=torch.float64)
            target[stream[t]] = 1.0
            if arm == 'A3-soft-frozenW':
                # dormancy: both specialist WEIGHTS stay at their initial
                # uniform-prior values; only the inverse covariances are
                # advanced on the current feature stream. (An rls_update with
                # zero error would leave W unchanged but would also advance P
                # once; here P is advanced exactly once, by rls_refresh_P.)
                P0 = rls_refresh_P(P0, phi)
                P1 = rls_refresh_P(P1, phi)
            else:
                W0, P0 = rls_update(W0, P0, phi, target, w0)
                W1, P1 = rls_update(W1, P1, phi, target, w1)

    stream_ppl = float(np.exp(np.nanmean(ce[1:])))
    neg_frac = float(nneg) / (T - 1)
    clip_frac = float(nclip) / (T - 1)
    stream_ppl_unclipped = (float(np.exp(np.nanmean(ce_unc[1:])))
                            if n_unc_undef < (T - 1) else float('nan'))
    if arm == 'A3-soft-frozenW':
        assert_W_still_frozen(W0, W0_init, arm, seed)
        assert_W_still_frozen(W1, W1_init, arm, seed)

    # T_adapt (s18 protocol, known switches)
    t_adapts = []
    switch_times = [SEG_LEN * s for s in range(1, N_SEGMENTS)]
    for si, t_s in enumerate(switch_times):
        seg_end = SEG_LEN * (si + 2) if si + 2 <= N_SEGMENTS else T
        seg_ce = ce[t_s:seg_end]
        if seg_ce.size == 0:
            continue
        steady = float(np.exp(np.mean(seg_ce[-STEADY_WINDOW:])))
        thr = steady * T_ADAPT_RATIO
        cum = np.concatenate([[0.0], seg_ce])
        found = None
        for j in range(T_ADAPT_WINDOW, seg_ce.shape[0] + 1):
            wppl = np.exp((cum[j] - cum[j - T_ADAPT_WINDOW])
                          / T_ADAPT_WINDOW)
            if wppl <= thr:
                found = j
                break
        t_adapts.append(float(found) if found is not None else float('nan'))

    # Forgetting: domain-matched specialist (A3) or single readout (A1)
    forgets = []
    forgets_unc = []
    fneg = 0
    fclip = 0
    n_f_undef = 0
    hold_ce_all = []
    hold_ce_unc_all = []
    for si, t_s in enumerate(switch_times):
        prev_dom = int(domains[t_s - 1])
        hold = gen_stream(seed * 41 + si * 211 + 3,
                          1 if prev_dom == 0 else 7, HOLDOUT_LEN,
                          BIAS_A if prev_dom == 0 else BIAS_B)
        hh = torch.zeros(N_STATE, dtype=torch.float64)
        if arm == 'A1':
            Wf = W
        else:
            Wf = W0 if prev_dom == 0 else W1
        ces = []
        ces_unc = []
        for t in range(1, HOLDOUT_LEN):
            hh = A * hh + B[:, hold[t - 1]]
            phi = torch.cat([B[:, hold[t - 1]],
                             torch.ones(1, dtype=torch.float64)])
            y_tok = (Wf @ phi)[hold[t]]
            p_t = float(y_tok.clamp(min=1e-12, max=1.0))
            yt = float(y_tok)
            if yt <= 0.0:
                fneg += 1
            if yt <= 1e-12:
                fclip += 1
            if yt > 0.0:
                ces_unc.append(-np.log(yt))
                hold_ce_unc_all.append(-np.log(yt))
            else:
                n_f_undef += 1
                hold_ce_unc_all.append(np.nan)
            ces.append(-np.log(p_t))
            hold_ce_all.append(-np.log(p_t))
        forgets.append(float(np.exp(np.mean(ces))))
        forgets_unc.append(float(np.exp(np.mean(ces_unc)))
                           if ces_unc else float('nan'))
    forgetting_ppl = float(np.mean(forgets))
    forgetting_ppl_unclipped = (float(np.nanmean(forgets_unc))
                                if forgets_unc else float('nan'))
    n_hold = (HOLDOUT_LEN - 1) * max(1, len(forgets))
    forget_neg_frac = float(fneg) / n_hold if n_hold else float('nan')
    forget_clip_frac = float(fclip) / n_hold if n_hold else float('nan')

    save_stream_and_holdout(
        's21', arm, seed, f'tau{tau_m:g}', ce, ce_unc,
        np.asarray(hold_ce_all, dtype=np.float64),
        np.asarray(hold_ce_unc_all, dtype=np.float64))

    return {'exp': 'E1', 'arm': arm, 'tau_m': float(tau_m), 'seed': seed,
            'stream_ppl': stream_ppl, 'neg_frac': neg_frac,
            't_adapt_mean': float(np.nanmean(t_adapts))
            if t_adapts else float('nan'),
            'forgetting_ppl': forgetting_ppl,
            'clip_frac': clip_frac,
            'stream_ppl_unclipped': stream_ppl_unclipped,
            'stream_n_unc_undefined': int(n_unc_undef),
            'forget_neg_frac': forget_neg_frac,
            'forget_clip_frac': forget_clip_frac,
            'forgetting_ppl_unclipped': forgetting_ppl_unclipped,
            'forget_n_unc_undefined': int(n_f_undef),
            'runtime_s': time.time() - t0}


# ========================== E2: M5 state-norm homeostat ==========================

def refs_full_reg(seed, A, B, scale, regulated):
    """Full-state metadata references, optionally under regulation."""
    refs = []
    for d in range(2):
        rs = gen_stream(seed * 31 + d * 131 + 7, 1 if d == 0 else 7,
                        REF_LEN, BIAS_A if d == 0 else BIAS_B)
        h = torch.zeros(N_STATE, dtype=torch.float64)
        acc = torch.zeros(N_STATE, dtype=torch.float64)
        dt = 1.0
        for t in range(REF_LEN):
            if regulated:
                h = torch.pow(A, dt) * h + B[:, rs[t]]
            else:
                h = A * h + B[:, rs[t]]
            hw = h * scale
            acc = acc + hw
            if regulated:
                n = float(torch.norm(hw))
                dt = min(max(dt + E2_ETA * (n - E2_U), 1.0), E2_DT_MAX)
        refs.append(acc / REF_LEN)
    return refs


def run_e2(args):
    """(reg, dist, seed) -> E2 metrics. Mechanism-level, honest scope."""
    if hasattr(sys.stdout, 'reconfigure'):
        sys.stdout.reconfigure(line_buffering=True)
        sys.stderr.reconfigure(line_buffering=True)
    reg, dist, seed = args
    arm = f"{'REG' if reg else 'BARE'}-{'dist' if dist else 'clean'}"
    t0 = time.time()

    torch.manual_seed(seed * SEED_SCALE + SEED_OFF)
    A, B = sample_substrate(seed, 'CV')
    scale = whiten_scale(A)
    stream, domains = gen_drift_stream(seed)
    T = stream.shape[0]

    refs = refs_full_reg(seed, A, B, scale, reg)
    slow = refs[0].clone()
    prev_est = 0
    flips = 0
    h = torch.zeros(N_STATE, dtype=torch.float64)
    dt = 1.0
    norms = np.empty(T, dtype=np.float64)
    dts = []
    spike_t = SEG_LEN
    recovery = None
    rng = np.random.RandomState(seed * 17 + 5)
    u = torch.from_numpy(rng.randn(N_STATE) / np.sqrt(N_STATE))

    for t in range(1, T):
        if reg:
            h = torch.pow(A, dt) * h + B[:, stream[t - 1]]
        else:
            h = A * h + B[:, stream[t - 1]]
        if dist and t == spike_t:
            h = h + E2_SPIKE * u
        hw = h * scale
        norms[t] = float(torch.norm(hw))
        if reg:
            dt = min(max(dt + E2_ETA * (norms[t] - E2_U), 1.0), E2_DT_MAX)
            dts.append(dt)
        # full-state EMA detector
        lam = 1.0 / TAU_M
        slow = (1.0 - lam) * slow + lam * hw
        est = gate_estimate(slow, refs, prev_est, GATE_MARGIN)
        if est != prev_est:
            flips += 1
            prev_est = est
        # recovery: first t after the spike with norm back in band
        if dist and recovery is None and t > spike_t and \
                norms[t] <= E2_U * E2_BAND:
            recovery = t - spike_t

    norm_mean = float(np.nanmean(norms[1:]))
    norm_max = float(np.nanmax(norms[1:]))
    norm_final = float(norms[-1])
    return {'exp': 'E2', 'arm': arm, 'reg': bool(reg), 'dist': bool(dist),
            'seed': seed, 'flips': int(flips), 'norm_mean': norm_mean,
            'norm_max': norm_max, 'norm_final': norm_final,
            'recovery_tokens': float(recovery) if recovery is not None
            else float('nan'),
            'dt_mean': float(np.mean(dts)) if dts else float('nan'),
            'dt_max': float(np.max(dts)) if dts else float('nan'),
            'runtime_s': time.time() - t0}


# ========================== Aggregation ==========================

def aggregate(results):
    groups = {}
    for r in results:
        groups.setdefault((r['exp'], r['arm']), []).append(r)
    agg = []
    for (exp, arm), rs in sorted(groups.items()):
        entry = {'exp': exp, 'arm': arm, 'n_runs': len(rs)}
        for m in rs[0]:
            if m in ('exp', 'arm', 'seed', 'runtime_s', 'reg', 'dist',
                     'tau_m'):
                continue
            v = np.array([r[m] for r in rs], dtype=float)
            v = v[~np.isnan(v)]
            entry[m + '_mean'] = float(np.mean(v)) if v.size else float('nan')
        if 'flips_mean' in entry:
            entry['flips_mean'] = float(np.mean([r['flips'] for r in rs]))
        agg.append(entry)
    return agg


def print_table(results):
    print("\n" + "=" * 110)
    print("S21 RESULTS (Paper D P3): M4 gentle routing (E1) + M5 "
          "state-norm homeostat (E2), 10 seeds")
    print("=" * 110)
    e1 = [r for r in results if r['exp'] == 'E1']
    e2 = [r for r in results if r['exp'] == 'E2']
    print("\nE1 (M4, tau_m=500):")
    print(f" {'arm':>10} | {'stream':>9} {'d_ppl':>9} {'n_imp':>5} | "
          f"{'forget':>9} {'d_forget':>9} {'n_imp':>5} | {'T_adapt':>8} "
          f"{'neg%':>5}")
    base = {r['seed']: r for r in e1 if r['arm'] == 'A1'}
    for arm in ['A1', 'A3-abrupt', 'A3-soft']:
        rs = [r for r in e1 if r['arm'] == arm]
        if not rs:
            continue
        ms = float(np.mean([r['stream_ppl'] for r in rs]))
        mf = float(np.mean([r['forgetting_ppl'] for r in rs]))
        if arm == 'A1':
            print(f" {arm:>10} | {ms:>9.3f} {'-':>9} {'-':>5} | "
                  f"{mf:>9.3f} {'-':>9} {'-':>5} | "
                  f"{np.nanmean([r['t_adapt_mean'] for r in rs]):>8.0f} "
                  f"{np.mean([r['neg_frac'] for r in rs]) * 100:>5.1f}")
            continue
        ds = np.array([r['stream_ppl'] - base[r['seed']]['stream_ppl']
                       for r in rs])
        df = np.array([r['forgetting_ppl']
                       - base[r['seed']]['forgetting_ppl'] for r in rs])
        print(f" {arm:>10} | {ms:>9.3f} {ds.mean():>+9.3f} "
              f"{int(np.sum(ds < 0)):>5}/10 | {mf:>9.3f} "
              f"{df.mean():>+9.3f} {int(np.sum(df < 0)):>5}/10 | "
              f"{np.nanmean([r['t_adapt_mean'] for r in rs]):>8.0f} "
              f"{np.mean([r['neg_frac'] for r in rs]) * 100:>5.1f}")
    # soft vs abrupt (the P3 prediction)
    sa = {r['seed']: r for r in e1 if r['arm'] == 'A3-abrupt'}
    so = {r['seed']: r for r in e1 if r['arm'] == 'A3-soft'}
    if sa and so:
        d = np.array([so[s]['stream_ppl'] - sa[s]['stream_ppl']
                      for s in so if s in sa])
        print(f" soft vs abrupt stream: {d.mean():+.3f}, soft better "
              f"{int(np.sum(d < 0))}/10")
        d = np.array([so[s]['forgetting_ppl'] - sa[s]['forgetting_ppl']
                      for s in so if s in sa])
        print(f" soft vs abrupt forget: {d.mean():+.3f}, soft better "
              f"{int(np.sum(d < 0))}/10")

    print("\nE2 (M5, full-state EMA detector; U=sqrt(N), eta=0.05, "
          "dt_max=10):")
    print(f" {'arm':>12} | {'flips':>6} | {'norm_mean':>9} "
          f"{'norm_max':>9} {'norm_final':>10} | {'recovery':>9} "
          f"{'dt_mean':>8} {'dt_max':>7}")
    for arm in ['BARE-clean', 'BARE-dist', 'REG-clean', 'REG-dist']:
        rs = [r for r in e2 if r['arm'] == arm]
        if not rs:
            continue
        print(f" {arm:>12} | "
              f"{np.mean([r['flips'] for r in rs]):>6.2f} | "
              f"{np.mean([r['norm_mean'] for r in rs]):>9.1f} "
              f"{np.mean([r['norm_max'] for r in rs]):>9.1f} "
              f"{np.mean([r['norm_final'] for r in rs]):>10.1f} | "
              f"{np.nanmean([r['recovery_tokens'] for r in rs]):>9.0f} "
              f"{np.mean([r['dt_mean'] for r in rs]):>8.2f} "
              f"{np.mean([r['dt_max'] for r in rs]):>7.1f}")


def load_e1_committed():
    """E1 rows of the committed s21 CSV, for paired comparison in the probe."""
    with open(CSV_PATH) as f:
        return [r for r in csv.DictReader(f) if r['exp'] == 'E1']


def dispatch(task):
    """Top-level Pool worker: (exp, args) -> run_e1 or run_e2."""
    exp, a = task
    return run_e1(a) if exp == 'E1' else run_e2(a)


def run_frozen_p_probe():
    """Isolation probe for dormant-covariance refresh.

    A3-soft (E1) trains both specialist readouts. This probe repeats the same
    integration with the weights frozen and only the inverse covariances
    refreshed, so the soft-routing stream cost can be split into the
    routing-rule change and the covariance refresh instead of being reported
    as one bundled flip. Writes its own file; does not touch the E1/E2
    artifacts.
    """
    t_start = time.time()
    print(f"[{time.strftime('%H:%M:%S')}] START S21 frozen-P probe "
          f"(A3-soft-frozenW, {N_SEEDS} seeds)")
    args = [('A3-soft-frozenW', TAU_M, s) for s in range(N_SEEDS)]
    rows = []
    for i, a in enumerate(args):
        rows.append(run_e1(a))
        print(f"[{time.strftime('%H:%M:%S')}] progress {i + 1}/{len(args)}",
              flush=True)

    def _delta(field, ref_arm):
        base = {r['seed']: r[field] for r in rows}
        ref = {int(r['seed']): float(r[field])
               for r in load_e1_committed() if r['arm'] == ref_arm}
        seeds = sorted(s for s in base if s in ref)
        d = np.array([base[s] - ref[s] for s in seeds])
        return {'vs': ref_arm,
                'diff_mean': float(d.mean()),
                'better_n': int(np.sum(d < 0)), 'n': int(d.size),
                'frozenW': {str(s): float(base[s]) for s in seeds},
                'reference': {str(s): float(ref[s]) for s in seeds}}

    out = {
        'params': {
            'experiment': 'dormant-covariance refresh isolation (P3 claim)',
            'arms': {'A3-soft': 'E1 reference (weights trained, s21 CSV)',
                     'A3-soft-frozenW': 'same softmax routing, weights frozen '
                                        'after the first token, inverse '
                                        'covariances refreshed each token'},
            'tau_m': TAU_M, 'n_seeds': N_SEEDS,
            'protocol': 'E1 verbatim (same task/seed rules as the s21 CSV)',
            'note': 'frozenW - A3-soft isolates the covariance refresh; '
                    'both are measured against the same per-seed A1 baseline',
            'env': {'torch': torch.__version__, 'numpy': np.__version__,
                    'cpu': 'torch CPU only'},
        },
        'stream_vs_a3soft': _delta('stream_ppl', 'A3-soft'),
        'stream_vs_a1': _delta('stream_ppl', 'A1'),
        'forgetting_vs_a3soft': _delta('forgetting_ppl', 'A3-soft'),
        'rows': rows,
    }
    out_path = os.path.join(DATA_DIR, 's37_dormant_p_probe_v1.json')
    with open(out_path, 'w') as f:
        json.dump(out, f, indent=2)
    d = out['stream_vs_a3soft']
    print(f"\nfrozenW - A3-soft stream: {d['diff_mean']:+.3f} "
          f"(frozenW better on {d['better_n']}/{d['n']})")
    print(f"JSON: {out_path}")
    check_paper_fixtures(out)
    print(f"[{time.strftime('%H:%M:%S')}] DONE, total "
          f"{time.time() - t_start:.1f}s")


def check_paper_fixtures(out):
    """Recompute the numbers Paper D quotes from committed data and report any
    drift from the constants at the top of this file (the manuscript's quoted
    values). Reports only; never rewrites the constants."""
    print("\n--- paper-fixture check (quoted values vs committed data) ---")
    problems = 0

    # (1) dormant-covariance isolation vs the probe that was just written
    fw = out['stream_vs_a3soft']['frozenW']
    worst = max(abs(float(v) - S37_CHANCE_PPL) for v in fw.values())
    ok = worst <= 1e-9
    problems += not ok
    print(f"  frozenW-only stream ppl: max|data - {S37_CHANCE_PPL:g}| = "
          f"{worst:.2e} over {len(fw)} seeds -> {'OK' if ok else 'DRIFT'} "
          "(the frozen arm must sit exactly at the uniform prior)")
    for label, key in [('frozenW - A3-soft stream', 'stream_vs_a3soft')]:
        d = out[key]
        if d['better_n'] != 0:
            problems += 1
            print(f"  {label}: expected the frozen arm to lose on all seeds, "
                  f"got better_n={d['better_n']} -> DRIFT")

    # (2) M3 detector counts and the detection-conditioned forgetting gain,
    #     both from the s20 CSV
    s20_path = os.path.join(DATA_DIR, 's20_ssm_m3_routing_v1.csv')
    rows = list(csv.DictReader(open(s20_path)))
    if rows and 'switches_detected' in rows[0]:
        a1 = {int(r['seed']): float(r['forgetting_ppl'])
              for r in rows if r['arm'] == 'A1'}
        for tm, const in S20_DETECTED.items():
            ds = [int(r['switches_detected']) for r in rows
                  if r['arm'] == 'A3' and float(r['tau_m']) == tm]
            got = sum(ds) / len(ds)
            ok = abs(got - const) <= 0.005
            problems += not ok
            print(f"  M3 detections tau_m={tm:g}: data {got:.2f}/5 vs paper "
                  f"{const:.2f} -> {'OK' if ok else 'DRIFT'}")
        det, nod = [], []
        for r in rows:
            if r['arm'] != 'A3':
                continue
            g = float(r['forgetting_ppl']) - a1[int(r['seed'])]
            (det if int(r['switches_detected']) > 0 else nod).append(g)
        for label, grp, const in [
                ('gain when detected >=1', det,
                 -S20_FORGET_GAIN_WHEN_DETECTED),
                ('gain when detected =0 ', nod, -S20_FORGET_GAIN_WHEN_NOT)]:
            got = sum(grp) / len(grp)
            ok = abs(got - const) <= 0.005
            problems += not ok
            print(f"  {label}: data {got:.4f} vs paper {const:.2f} "
                  f"-> {'OK' if ok else 'DRIFT'}")
    else:
        print("  s20 CSV has no switches_detected column -> re-run "
              "s20_ssm_m3_routing.py to enable this check")
    print(f"--- {problems} drift(s) ---")


def main():
    if '--frozen-p-probe' in sys.argv:
        run_frozen_p_probe()
        return
    quick = '--quick' in sys.argv
    sequential = '--sequential' in sys.argv
    t_start = time.time()
    print(f"[{time.strftime('%H:%M:%S')}] START S21 M4+M5 (quick={quick}, "
          f"sequential={sequential})")

    n_seeds = 1 if quick else N_SEEDS
    e1_args = [(arm, TAU_M, s) for arm in ['A1', 'A3-abrupt', 'A3-soft']
               for s in range(n_seeds)]
    e2_args = [(reg, dist, s) for reg in [False, True]
               for dist in [False, True] for s in range(n_seeds)]
    all_args = [('E1', a) for a in e1_args] + [('E2', a) for a in e2_args]
    n_runs = len(all_args)
    print(f"total runs: {n_runs} (E1 {len(e1_args)}, E2 {len(e2_args)})")

    results = []
    if sequential:
        for i, (exp, a) in enumerate(all_args):
            results.append(run_e1(a) if exp == 'E1' else run_e2(a))
            if (i + 1) % max(1, n_runs // 10) == 0 or (i + 1) == n_runs:
                print(f"[{time.strftime('%H:%M:%S')}] progress {i + 1}/{n_runs}",
                      flush=True)
    else:
        with Pool(min(cpu_count(), max(1, n_runs))) as pool:
            done = 0
            for res in pool.imap_unordered(dispatch, all_args, chunksize=1):
                results.append(res)
                done += 1
                if done % max(1, n_runs // 10) == 0 or done == n_runs:
                    print(f"[{time.strftime('%H:%M:%S')}] progress {done}/{n_runs}",
                          flush=True)

    print_table(results)

    os.makedirs(DATA_DIR, exist_ok=True)
    fieldnames = ['exp', 'arm', 'tau_m', 'seed', 'stream_ppl', 'neg_frac',
                  't_adapt_mean', 'forgetting_ppl', 'flips', 'norm_mean',
                  'norm_max', 'norm_final', 'recovery_tokens', 'dt_mean',
                  'dt_max', 'clip_frac', 'stream_ppl_unclipped',
                  'stream_n_unc_undefined', 'forget_neg_frac',
                  'forget_clip_frac', 'forgetting_ppl_unclipped',
                  'forget_n_unc_undefined', 'runtime_s']
    out_csv = CSV_PATH if not quick else CSV_PATH.replace('.csv', '_quick.csv')
    with open(out_csv, 'w', newline='') as f:
        w = csv.DictWriter(f, fieldnames=fieldnames, extrasaction='ignore')
        w.writeheader()
        w.writerows(results)

    params = {
        'host': 'diagonal linear SSM (N=128), CV spectrum, whitened; '
                'readout = RLS on [B e; 1] (P1/P3a host)',
        'e1_m4': {'tau_m': TAU_M,
                  'arms': {'A1': 'bare single RLS readout',
                           'A3-abrupt': 'P2 routing replication '
                                        '(hysteresis flip)',
                           'A3-soft': 'softmax-distance weighted routing, '
                                      'kappa = 0.5*||ref0-ref1|| (gentle)'},
                  'prediction': 'soft < abrupt on stream ppl, forgetting '
                                'not degraded (P3: gradual beats abrupt)'},
        'e2_m5': {'controller': 'Delta_t = clip(Delta_t + eta*(||h_w||-U), '
                                '1, dt_max); h_t = A^{Delta_t} h_{t-1} + B e',
                  'U': E2_U, 'eta': E2_ETA, 'dt_max': E2_DT_MAX,
                  'band': E2_BAND, 'spike': E2_SPIKE,
                  'prediction': 'REG keeps norm in band and restores the '
                                'full-state EMA detector (5/5); BARE drifts '
                                '(P4)'},
        'task': 'identical to s18: two biased-bigram generators, known '
                'switches, 6x3000; seed rules verbatim',
        'metrics': {'E1': 'stream ppl / forgetting ppl / T_adapt / neg_frac '
                         '/ clip_frac / unclipped sensitivity diagnostics '
                         '(s18 protocol)',
                    'E2': 'full-state EMA detector flips, norm mean/max/final, '
                          'recovery tokens, dt activity (mechanism-level)'},
        'discipline': '10 seeds, paired sign consistency',
        'env': {'torch': torch.__version__, 'numpy': np.__version__,
                'cpu': 'torch CPU only, no mamba-ssm dependency'},
        'n_seeds': n_seeds, 'quick': bool(quick),
    }
    out_json = JSON_PATH if not quick else JSON_PATH.replace('.json', '_quick.json')
    payload = _nan_to_null({'params': params, 'aggregates': aggregate(results),
                            'null_reason': ('non-finite aggregate values are '
                                            'written as null (undefined, e.g. a '
                                            'cell in which the adaptation '
                                            'criterion was never met, so '
                                            'recovery_tokens, dt_mean and '
                                            'dt_max have no measurement)')})
    with open(out_json, 'w') as f:
        json.dump(payload, f, indent=2, allow_nan=False)

    print(f"\nCSV : {out_csv}")
    print(f"JSON: {out_json}")
    print(f"[{time.strftime('%H:%M:%S')}] DONE, total {time.time() - t_start:.1f}s")


def _nan_to_null(obj):
    """Recursively map non-finite floats to None (strict-JSON safe).

    Bug fix 2026-09-09 (dedup P1-90): json.dump wrote bare NaN literals for
    undefined aggregates (recovery_tokens / dt_mean / dt_max of a cell in which
    the adaptation criterion was never met), which is not valid JSON and is
    rejected by strict parsers.
    """
    if isinstance(obj, dict):
        return {k: _nan_to_null(v) for k, v in obj.items()}
    if isinstance(obj, (list, tuple)):
        return [_nan_to_null(v) for v in obj]
    if isinstance(obj, float) and not np.isfinite(obj):
        return None
    return obj


if __name__ == '__main__':
    main()
